### ISSUE TITLE
"Welcome to nginx!"

### ISSUE THREAD

**Issue by dimzeta** [tangramor/nginx-php8-fpm#2]
Firstly, thank you for your docker setup, it is really helpful.

I try to use it with my Laravel project, and when I access to http://localhost I have the initial Nginx page: "Welcome to nginx!".

I can access to the DB manually, mailhog interface etc, but I don't know why I have the initial page instead of my project.

My project is in the container, in the `/var/www/html` folder:

```sh
❯ docker exec -it 8cd67828639c31f23848af5e61c543f6b2f16a46a61d2d27e67bde06da6a9b18 /bin/sh
/var/www/html # ls -alh
total 936K
drwxr-xr-x 27 root  root   864 Jan  4 20:44 .
drwxr-xr-x  3 root  root  4.0K Nov 13 08:48 ..
-rw-r--r--  1 root  root   608 Jan  4 22:21 .env
-rw-r--r--  1 root  root   521 Nov  8 14:37 .env.example
drwxr-xr-x 13 root  root   416 Jan  4 21:44 .git
-rw-r--r--  1 root  root   111 Nov  8 14:37 .gitattributes
-rw-r--r--  1 root  root   156 Nov  8 14:37 .gitignore
drwxr-xr-x  7 root  root   224 Nov  8 14:37 app
-rw-r--r--  1 root  root  1.7K Nov  8 14:37 artisan
drwxr-xr-x  5 root  root   160 Nov  8 14:37 bootstrap
-rw-r--r--  1 root  root  1.2K Nov  8 15:00 composer.json
-rw-r--r--  1 root  root  132K Nov  8 14:37 composer.lock
drwxr-xr-x 13 root  root   416 Nov  8 14:37 config
drwxr-xr-x  6 root  root   192 Nov  8 14:37 database
-rw-r--r--  1 root  root  1.8K Jan  4 22:24 docker-compose.yml
-rw-r--r--  1 root  root  541K Nov  8 14:37 package-lock.json
-rw-r--r--  1 root  root  1.1K Nov  8 14:37 package.json
-rw-r--r--  1 root  root  1.1K Nov  8 14:37 phpunit.xml
drwxr-xr-x 11 root  root   352 Nov  8 14:37 public
drwxr-xr-x  5 root  root   160 Nov  8 14:37 resources
drwxr-xr-x  6 root  root   192 Nov  8 14:37 routes
-rw-r--r--  1 root  root   563 Nov  8 14:37 server.php
drwxr-xr-x  5 nginx nginx  160 Nov  8 14:37 storage
drwxr-xr-x  6 root  root   192 Nov  8 14:37 tests
drwxr-xr-x 34 root  root  1.1K Nov  8 15:00 vendor
-rw-r--r--  1 root  root   549 Nov  8 14:37 webpack.mix.js
-rw-r--r--  1 root  root  209K Nov  8 14:37 yarn.lock
```

Here is my docker-compose, but it's simply the same as yours excepted I'm using Mysql 8.0:

```yaml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        image: tangramor/nginx-php8-fpm
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            TZ: 'Europe/Paris'
            WEBROOT: '/var/www/html/public'
            PHP_REDIS_SESSION_HOST: 'redis'
            CREATE_LARAVEL_STORAGE: '1'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
  
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    redis:
        image: 'redis:alpine'
        #ports:
        #    - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]

    memcached:
        image: 'memcached:alpine'
        ports:
            - '11211:11211'
        networks:
            - sail

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
```

Thank you!
